### ISSUE TITLE
Trace files

### ISSUE THREAD

**Issue by ATCP** [vishal1303/Shoal#1]
Hi,  

I have a question about the trace:

where can I get the trace files to reproduce your simulated experiments in the paper, thanks

looking forward to your response

Ke

**Comment by vishal1303** [comment]
Hi. I have updated the README with instructions on how to reproduce simulated experiments in the paper.

**Comment by ATCP** [comment]
Hi, from your paper, you used the trace from osdi16 paper. I find they have four sets of traces:
for example:
0-disk-ec2-54-197-111-1.compute-1.amazonaws.com.blktrace.0.txt	 
*0-mem-ec2-54-197-111-1.compute-1.amazonaws.com.merged*
0-meta-ec2-54-197-111-1.compute-1.amazonaws.com
0-nic-ec2-54-197-111-1.compute-1.amazonaws.com

which set of trace you are using to produce your own trace, is it mem trace?

in their mem trace, it has five columns. from my understanding, they mean

> batch_id, timestamp (in millisecond), start memory address (+ write, - read), length of request (the number of pages (4KB)). 

am I correct?

I grab one line your trace from memcached.csv
0,72,267,4620,4.06683477701e-09
where flow size is 4620, does it mean src node 72 write 4KB page to the dest node 267, and you have 620 Byte header size, do I understand correctly?

Sorry to disturb you with many questions, Thanks for your time

Ke

**Comment by vishal1303** [comment]
To generate the trace, we use the same methodology as described in the osdi paper in Section 4.1. These traces are flow level traces, and do not distinguish between the actual "type" of flow, i.e., memory flow, disk flow etc. The network does not care about the "type" of flow. They just see data to be sent from node A to B. So, each line in the trace file simply means:
0,72,267,4620,4.06683477701e-09
There is a flow of size 4620 Bytes sourced at node 72 and destined to node 267 and the flow started at time 4.06683477701e-09 sec.

**Comment by ATCP** [comment]
Thanks for the response
so you generate your own trace instead of using the original trace from osdi16 paper

**Comment by vishal1303** [comment]
We derive the flow distribution from the osdi traces which was for a small number of nodes in their emulation testbed, and extrapolate those traces to 512 nodes for our experiments. But our traces have the same flow distribution as the osdi paper.

**Comment by ATCP** [comment]
ok, Thanks
but I am curious which set of osdi trace used to derive the flow distribution. 
As mentioned in the previous posts, there are four sets of trace, e.g., 

> 0-disk-ec2-54-197-111-1.compute-1.amazonaws.com.blktrace.0.txt
> 0-mem-ec2-54-197-111-1.compute-1.amazonaws.com.merged
> 0-meta-ec2-54-197-111-1.compute-1.amazonaws.com
> 0-nic-ec2-54-197-111-1.compute-1.amazonaws.com

for mem trace, I can understand what it is inside, but for the other three, I don't know what trace is
Could you kindly briefly explain how do you generate the flow distribution. Thanks a lot

Regards,
Ke

**Comment by vishal1303** [comment]
We got the flow distribution trace from the authors of the osdi paper and simply extrapolated it.

**Comment by ATCP** [comment]
ok, thanks

**Comment by ATCP** [comment]
Hi, I understand your trace includes the network traffic from memory and disk, do you have any idea of the ratio of the memory flow and disk flow

**Comment by vishal1303** [comment]
Hi. Unfortunately the tracefiles we got from osdi authors was not annotated with the "type" of flow. So we do not have stats on the ratio of different kinds of flows in our tracefiles.

**Comment by ATCP** [comment]
Ok, Thanks
